#ifndef GAME_SCREENS_H
#define GAME_SCREENS_H

typedef enum {
    GAME_SCREEN_NONE,
    GAME_SCREEN_TITLE,
    GAME_SCREEN_LEVEL_SELECT,
    GAME_SCREEN_PLAYING,
    GAME_SCREEN_TUTORIAL,
    GAME_SCREEN_SETTINGS
} GameScreen;

#endif