#ifndef STATES_H
#define STATES_H

typedef enum {
    GAME_STATE_NONE,
    GAME_STATE_TITLE,
    GAME_STATE_LEVEL_SELECT,
    GAME_STATE_PLAYING,
    GAME_STATE_TUTORIAL,
    GAME_STATE_SETTINGS
} GameState;

#endif